<?php
include 'top.php';
?>
        <main id="index">
            <figure class="rightFig">
                <img alt="A wind turbine" src="../images/turbine.jpg">
                <figcaption>
                    An electricity-generating wind turbine<br>
                    <cite>Source: PXHere</cite>
                </figcaption>
            </figure>

            <section class="Types">
                <h2>Types of Green Energy</h2>
                <p>
                    There exist many varieties of green energy. Among the most prevalent
                    are solar, wind, hydro, geothermal, and nuclear. In contrast to traditional
                    fossil-fuel sources, green energy outputs comparatively little (if any) greenhouse
                    gases.
                </p> 
                <ul>
                    <li>Solar energy is generated by converting sunlight to electricity.</li>
                    <li>Wind energy is generated by using the force of the wind to spin a turbine.</li>
                    <li>Geothermal energy is generated by using steam and the heat of the Earth.</li>
                    <li>Nuclear energy exploits the radioactive decay of certain elements.</li>
                    <li><cite>Source: my own knowledge.</cite></li>
                </ul>
            </section>

            <section class="Drawbacks">
                <h2>Drawbacks of Traditional Energy</h2>
                <p>
                    As aforementioned, the most significant drawback to traditional, fossil-fuel energy sources
                    are the greenhouse gas emissions they produce. The same chemical reactions that occur when
                    these fuels (coal, oil, natural gas, etc.) are burnt to generate electricity also release 
                    carbon dioxide, methane, and other warming gases. While energy-dense, relatively cheap, and
                    plentifully available, fossil fuels heat the earth, thereby changing the climate.
                </p>

                <table>
                    <caption>United States electricity generation by source, 2021</caption>
                    <tr><th>Source</th><th>Share of total generation</th><th>+/- compared to 2020</th></tr>

                    <?php
                    $sql = 'SELECT fldSource, fldShare, fldGainLoss FROM tblEnergyData ORDER BY fldShare DESC';
                    $statement = $pdo->prepare($sql);
                    $statement->execute();

                    $records = $statement->fetchAll();

                    foreach($records as $record) {
                        print '<tr>';
                        print '<td>' . $record['fldSource'] . '</td>';
                        print '<td>' . $record['fldShare'] . '%</td>';
                        print '<td>' . $record['fldGainLoss'] . '%</td>';
                        print '</tr>' . PHP_EOL;
                    }
                    ?>

                    <tr><td colspan="3"><cite><a href="https://www.eia.gov/environment/emissions/carbon/">Source: U.S. Energy Information Administration</a></cite></td></tr>
                </table>
            </section>

            <section class="Environmental-benefits">
                <h2>Environmental Benefits of Green Energy</h2>
                <p>
                    Beyond reducing emissions, there are further environmental benefits of green energy.
                    In addition to greenhouse gases, fossil fuel burning often results in extremely
                    harmful, difficult to dispose byproducts, such as coal sludge and fracking waste.
                    Often, these substances find their ways into the natural environment, harming ecosystems
                    and dirtying water supplies. Green energy mostly avoids similar outputs. 
                </p>
            </section>
            
            <section class="Cost-benefits">
                <h2>Cost Benefits of Green Energy</h2>
                <p>
                    While fossil fuels are very energy dense for the cost needed to extract them, green energy
                    offers often comparable or better price benefits. Onshore wind, hydropower, and solar power
                    offer similar, if not better, cost per kilowatt-hour. When factoring in the costs associated
                    with climate change, green energy has a strong financial argument. 
                    <cite> Source: Our World in Data </cite>
                </p>
            </section>
        </main>

        <?php
        include 'footer.php';
        ?> 
    </body> 
</html>